INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (NAME, CREATED_AT) VALUES ('Computers', NOW());
